twig:
    default_path: '%kernel.project_dir%/src/UserInterface/Web/Templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        staticData: '@Cafe\UserInterface\Web\StaticData\StaticData'
        activeTables: '@Cafe\Application\Read\OpenTabsQueries'
