
version: "3.1"
services:
  php-fpm:
    image: devilbox/php-fpm-7.4
    container_name: cqrs.nu-fpm
    working_dir: /application
    volumes:
      - .:/application
    ports:
    - 8000:8000
    entrypoint: "php -S 0.0.0.0:8000 -t public"